import { createContext } from "react";
import type { Annotation, AnnotationRect, MarkupType } from "../../annotations";
import type { PdfDocument } from "../../documents";
import type { PdfNavigationTarget } from "../types/pdfNavigation";
import type { PdfBookmark, PdfBookmarkDraft } from "../types/pdfBookmark";

export type PdfZoomMode = "custom" | "fit-width" | "fit-page";
export type PdfInteractionMode = "pointer" | "pan" | "markup" | "area" | "eraser";

export type PdfWorkspaceContextValue = {
  documents: PdfDocument[];
  activeDocument: PdfDocument | null;
  activeDocumentId: string | null;
  annotations: Annotation[];
  bookmarks: PdfBookmark[];
  movingBookmarkId: string | null;
  transformingAreaId: string | null;
  scale: number;
  zoomMode: PdfZoomMode;
  currentPage: number;
  navigationTarget: PdfNavigationTarget | null;
  sidebarCollapsed: boolean;
  annotationPanelCollapsed: boolean;
  selectedAnnotationId: string | null;
  activeMarkupType: MarkupType;
  interactionMode: PdfInteractionMode;
  activeAnnotationColor: string;
  canNavigateHistoryBack: boolean;
  canNavigateHistoryForward: boolean;
  canUndoAnnotations: boolean;
  canRedoAnnotations: boolean;
  openFile: () => Promise<void>;
  saveActiveDocument: () => Promise<void>;
  saveActiveDocumentAs: () => Promise<void>;
  exportNotes: () => Promise<void>;
  activateDocument: (id: string) => void;
  closeDocument: (id: string) => void;
  closeOtherDocuments: (id: string) => void;
  reorderDocuments: (sourceId: string, targetId: string) => void;
  copyDocumentPath: (id: string) => void;
  setScale: (scale: number) => void;
  fitToWidth: () => void;
  fitToPage: () => void;
  resolveFitScale: (scale: number) => void;
  setCurrentPage: (page: number, pageY?: number, pageX?: number) => void;
  navigateToPage: (page: number) => void;
  navigateToOutline: (page: number, title: string) => Promise<void>;
  navigateToSearchResult: (page: number, pageY: number) => void;
  navigateToLink: (page: number, pageX?: number, pageY?: number) => void;
  openExternalLink: (uri: string) => Promise<void>;
  navigateHistoryBack: () => void;
  navigateHistoryForward: () => void;
  toggleSidebar: () => void;
  toggleAnnotationPanel: () => void;
  captureSelection: (selection: PdfTextSelection) => void;
  clearSelection: () => void;
  applyMarkup: (type: MarkupType, selection?: PdfTextSelection) => void;
  selectPointerTool: () => void;
  selectPanTool: () => void;
  selectMarkupTool: (type: MarkupType) => void;
  selectAreaTool: () => void;
  selectEraserTool: () => void;
  addNote: (selection?: PdfTextSelection) => void;
  selectAnnotation: (id: string | null) => void;
  navigateToAnnotation: (id: string) => void;
  previewAnnotationColor: (color: string) => void;
  setAnnotationColor: (color: string) => void;
  convertAnnotation: (id: string, type: MarkupType) => void;
  updateAnnotation: (annotation: Annotation) => void;
  addAreaAnnotation: (page: number, rect: AnnotationRect) => void;
  beginAreaTransform: (id: string | null) => void;
  deleteAnnotation: (id: string) => void;
  undoAnnotations: () => void;
  redoAnnotations: () => void;
  mergeAnnotations: (ids: string[]) => void;
  addBookmark: (bookmark: PdfBookmarkDraft) => void;
  updateBookmark: (id: string, changes: Partial<Pick<PdfBookmark, "title" | "color" | "page" | "x" | "y">>) => void;
  deleteBookmark: (id: string) => void;
  clearBookmarks: (page?: number) => void;
  beginBookmarkMove: (id: string | null) => void;
  navigateToBookmark: (id: string) => void;
};

export type PdfTextSelection = { page: number; text: string; rects: AnnotationRect[] };

export const PdfWorkspaceContext = createContext<PdfWorkspaceContextValue | null>(null);
